spring:
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12804047?createTableIfNotExists=true
    username: sql12804047
    password: jhB2kcKm5E
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com
    port: 587
    username: azmaan000@gmail.com
    password: vitikdvnfvnclybk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true